[package]
name = "garden_scenes_component"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
garden = { path = "../../garden" }
garden_loading = { path = "../../loading" }
garden_json_component = { path = "../../json/component" }
garden_scenes = { path = "../scenes" }
garden_scenes_loading = { path = "../loading" }
garden_winit = { path = "../../winit" }