[package]
name = "garden"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mockall = "0.11.3"
glutin = "0.30.1"

[build-dependencies]
gl_generator = "0.14"
cfg_aliases = "0.1.1"