[package]
name = "garden_glutin_example_2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
garden = { path = "../../garden" }
garden_games = { path = "../../games" }
garden_glutin = { path = "../../glutin" }
garden_json_component = { path = "../../json/component" }
garden_winit = { path = "../../winit" }
garden_content_component = { path = "../../content/component" }
garden_maths_component = { path = "../../maths/component" }
garden_scenes_component = { path = "../../scenes/component" }
winit = "0.27.5"